[metadata]
    Title = "IT Club"
    description = "" 

[tool-setting]
    file-with-date = 1
    contentDirPath = "./content"
    publicDirPath = "./public"
    sourceDirPath = "./src"
    img_dir = "./img"
    template_dir = "./template/design"
    news_dir = "./public/content/news"
    templateNewsFile = "./template/news.html"
    news_outputPath = "./public/content/news.html"